apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voteapp
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: voteapp
    repoURL: "https://github.com/AmiirEbadi/voteapp_kubernetes.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
